# Generated by Django 5.2.5 on 2025-08-23 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='data',
            field=models.DateField(default=datetime.datetime(2025, 8, 23, 21, 16, 26, 783509, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data',
            field=models.DateField(default=datetime.datetime(2025, 8, 23, 21, 16, 26, 783225, tzinfo=datetime.timezone.utc)),
        ),
    ]
