# Generated by Django 5.2.5 on 2025-08-23 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_despesa_data_alter_receita_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='data',
            field=models.DateField(default=datetime.datetime(2025, 8, 23, 21, 17, 48, 580297, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data',
            field=models.DateField(default=datetime.datetime(2025, 8, 23, 21, 17, 48, 580000, tzinfo=datetime.timezone.utc)),
        ),
    ]
