# Generated by Django 5.2.5 on 2025-08-23 21:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_despesa_data_alter_receita_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
